# Generated by Django 5.1.1 on 2024-10-30 00:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='Fecha_Ingreso',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 29, 18, 3, 54, 515584)),
        ),
        migrations.AlterField(
            model_name='productos',
            name='Estado',
            field=models.BooleanField(default=True),
        ),
    ]
